config/routes.rb
Rails.application.routes.draw do
  #rootを受講生ログイン画面に設定
  devise_scope :student do
    root 'therapist_training_course#index', as: :public_root, constraints: LoggedInConstraint.new("therapist_training")
    root 'self_care_course#index', constraints: LoggedInConstraint.new("self_care")
    root 'admin_screen#index', constraints: LoggedInConstraint.new("true")
    root 'staffs_screen#index', constraints: LoggedInConstraint.new("false")
    root "students/sessions#new", constraints: LoggedInConstraint.new("")
  end

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }
  devise_for :students, :controllers => {
    :sessions => 'students/sessions'
  }

  get 'therapist_training_course' => 'therapist_training_course#index', as: :therapist_training_course#セラピスト養成コース画面トップページ
  get 'self_care_course' => "self_care_course#index", as: :self_care_course#セルフケアコース画面トップページ
  get 'therapist_training_course/:id' => 'therapist_training_course#show', as: :therapist_training_course_show#セラピスト養成コース マイページ
  get 'self_care_course/id' => 'self_care_course#show', as: :self_care_course_show#セルフケアコース マイページ

  get 'admin_screen' => 'admin_screen#index', as: :admin_screen#管理者画面
  get 'staffs_screen' => 'staffs_screen#index', as: :staffs_screen#スタッフ画面

  resources :staffs do
    resources :blogs #スタッフブログ
  end

  resources :schedules#開講スケジュール

  resources :students#ユーザー管理

  resources :uploads, only: [:create, :destroy]

  resources :backgrounds#背景画像選択

  get 'serapoke' => 'serapoke#index', as: :serapoke#せらポケ

  get 'diploma' => 'diploma#index', as: :diploma#ディプロマ

  get '/admin/:student_id/student_edit' => 'admins#student_edit', as: :student_edit_admin#student編集

  post '/students/import' => 'students#import', as: :import_students#csvファイル取り込み

end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: true
end

app/controllers/staffs/registrations_controller.rb
# frozen_string_literal: true

class Staffs::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:cancel]
  before_action :creatable?, only: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def creatable?
    redirect_to root_url unless staff_signed_in?
    if !current_staff_is_admin?
      redirect_to staffs_screen_url, alert: "権限がありません"
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # def create
  #   # ここでStaff.new（と同等の操作）を行う
  #   build_resource(sign_up_params)

  #   # ここでStaff.save（と同等の操作）を行う
  #   resource.save

  #   # ブロックが与えられたらresource(=Staff)を呼ぶ
  #   yield resource if block_given?
  #   if resource.persisted?
  #   # 先程のresource.saveが成功していたら
  #     if resource.active_for_authentication?
  #     # confirmable/lockableどちらかのactive_for_authentication?がtrueだったら
  #       # flashメッセージを設定
  #       set_flash_message! :notice, :signed_up
  #       # サインアップ操作
  #       sign_up(resource_name, resource)
  #       # リダイレクト先を指定
  #       respond_with resource, location: staff_after_sign_up_path_for(resource)
  #     else
  #       set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
  #       # sessionを削除
  #       expire_data_after_sign_in!
  #       respond_with resource, location: after_inactive_sign_up_path_for(resource)
  #     end
  #   else
  #   # 先程のresource.saveが失敗していたら
  #     # passwordとpassword_confirmationをnilにする
  #     clean_up_passwords resource
  #     # validatable有効時に、パスワードの最小値を設定する
  #     set_minimum_password_length
  #     respond_with resource
  #   end
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def current_staff_is_admin?
    staff_signed_in? && current_staff.admin?
  end

  def sign_up(resource_name, resource)
    if !current_staff_is_admin?
      sign_in(resource_name, resource)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    staffs_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    staffs_path(resource)
  end
end

app/controllers/staffs/sessions_controller.rb
class Staffs::SessionsController < Devise::SessionsController

  def create
    #元の認証ロジック
    #self.resource = warden.authenticate!(auth_options)

    #emailだけでログインできるように変更
    
    if params[:staff]['email'].present?
      self.resource = Staff.where(:email => params[:staff]['email']).first
      if self.resource.present?
        set_flash_message(:notice, :signed_in) if is_flashing_format?
        sign_in(resource_name, resource)
        yield resource if block_given?
        if self.resource.admin == false
          session[:student_id] = "false"
          respond_with resource, :location => staff_after_sign_in_path_for(resource)
        elsif self.resource.admin == true
          session[:student_id] = "true"
          respond_with resource, :location => admin_after_sign_in_path_for(resource)
        end
      else
        flash[:danger] = "Eメールが違います"
        redirect_to new_staff_session_path
      end
    else
      flash[:danger] = "Eメールを入力してください"
      redirect_to new_staff_session_path
    end
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  # オブジェクトの準備
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  # アクセス制限
  before_action :admin_only, only: [:index, :show, :edit, :update, :destroy]
  
  def index
    @staffs = Staff.order(created_at: "ASC").paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def edit
  end

  def update
    if @staff.update_attributes(staff_params)
      flash[:success] = "スタッフ情報を更新しました。"
      redirect_to @staff
    else
      render :template=> "staffs/edit", :locals=> { :@staff=> @staff }
   end
  end

  def destroy
    @staff.destroy
    flash[:success] = "「#{@staff.name}」のデータを削除しました。"
    redirect_to staffs_url
  end

  private

  def set_staff
    @staff = Staff.find(params[:id])
  end

  def staff_params
    params.require(:staff).permit(:name, :email)
  end


end

app/helpers/staffs_helper.rb
module StaffsHelper

    # 管理者・スタッフログイン時のパスの切り分け
    def staff_toppage_routes(staff)
      return admin_screen_path if staff.admin == true
      return staffs_screen_path if staff.admin == false
    end
  
end

app/views/staffs/_form.html.erb
<%= form_with(model: @staff, local: true) do |f| %>
  <%= render 'devise/shared/error_messages', resource: @staff %>

  <%= f.label :name, class: "staff--edit" %>
  <%= f.text_field :name, class: "form-control staff--edit" %>

  <%= f.label :email, class: "staff--edit" %>
  <%= f.email_field :email, class: "form-control staff--edit" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-staff--edit btn-resize" %>
<% end %>

app/views/staffs/edit.html.erb
<% provide(:class_text, 'staff--edit') %>
<% provide(:button_text, '編集') %>
<div class="container col-10 col-md-10 col-lg-6">
  <div class="staff--title">
    <h1>スタッフ情報の更新</h1>
    <%= render 'staffs/form' %>
  </div>
  <br>
  <%= link_to "戻る", 'javascript:history.back()', class: "btn btn-secondary btn-resize" %>
</div>

app/views/staffs/index.html.erb
<div class="staff--title">
  <%= render 'layouts/flash_messages' %>
  <h1>スタッフ一覧</h1>
</div>
<div class="container">
  <%= link_to "スタッフ新規登録", new_staff_registration_path, class: "btn btn-primary btn-sm" %>
</div>  

<div class="container">
  <% @staffs.each_with_index do |staff, n| %>
    <div class="row">
      <div class="d-flex align-items-center border-top border-dark  staff--index col-3">
        名前:
      </div>
      <div class="d-flex align-items-center border-top border-dark staff--index col-5">
        <%= link_to staff.name, edit_staff_path(staff), class: "edit#{n}" %>
      </div>
      <% if current_staff.present? && current_staff.admin == true %>
        <div class="border-top d-flex align-items-center border-dark staff--index col-2">
          <%= link_to "詳細", staff_path(staff), class: "btn btn-info btn--resize show#{n}" %>
        </div>
        <div class="border-top d-flex align-items-center border-dark staff--index col-2">
          <%= link_to "削除", staff_path(staff), method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn-danger btn--resize delete#{n}" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="d-flex align-items-center border-top staff--index col-3">
        Eメール:
      </div>
      <div class="border-top d-flex align-items-center staff--index col-9">
        <%= staff.email %>
      </div>
    </div>
  <% end %>
</div>
<br>
<%= will_paginate(@pusers, :previous_label => ' &lt 前へ', :next_label => '次へ &gt', class: "pagination justify-content-center mt-6 mb-7 btn--resize", renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
<%= link_to "戻る", admin_screen_path, class: "btn btn-secondary btn-resize" %>

app/views/staffs/show.html.erb
<div class="staff--title">
  <%= render 'layouts/flash_messages' %>
  <h1>スタッフ詳細</h1>
</div>
<div class="container">
  <div class="row">
    <div class="d-flex align-items-center border staff--show col-3">
      名前:
    </div>
    <div class="d-flex align-items-center border-right border-top border-bottom staff--show col-9">
      <%= @staff.name %>
    </div>
  </div>
  <div class="row">
    <div class="d-flex align-items-center border staff--show col-3">
      Eメール:
    </div>
    <div class ="d-flex align-items-center border-right border-top border-bottom staff--show col-9">
      <%= @staff.email %>
    </div>
  </div>
</div>
<br>
<%= link_to "戻る", staffs_path, class: "btn btn-secondary btn--resize" %>