config/routes.rb
Rails.application.routes.draw do
  #rootを受講生ログイン画面に設定
  devise_scope :student do
    root 'therapist_training_course#index', as: :public_root, constraints: LoggedInConstraint.new("therapist_training")
    root 'self_care_course#index', constraints: LoggedInConstraint.new("self_care")
    root 'admin_screen#index', constraints: LoggedInConstraint.new("true")
    root 'staffs_screen#index', constraints: LoggedInConstraint.new("false")
    root "students/sessions#new", constraints: LoggedInConstraint.new("")
  end

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }
  devise_for :students, :controllers => {
    :sessions => 'students/sessions'
  }

  get 'therapist_training_course' => 'therapist_training_course#index', as: :therapist_training_course#セラピスト養成コース画面トップページ
  get 'self_care_course' => "self_care_course#index", as: :self_care_course#セルフケアコース画面トップページ
  get 'therapist_training_course/:id' => 'therapist_training_course#show', as: :therapist_training_course_show#セラピスト養成コース マイページ
  get 'self_care_course/id' => 'self_care_course#show', as: :self_care_course_show#セルフケアコース マイページ

  get 'admin_screen' => 'admin_screen#index', as: :admin_screen#管理者画面
  get 'staffs_screen' => 'staffs_screen#index', as: :staffs_screen#スタッフ画面

  resources :staffs do
    resources :blogs #スタッフブログ
  end

  resources :schedules#開講スケジュール

  resources :students#ユーザー管理

  resources :uploads, only: [:create, :destroy]

  resources :backgrounds#背景画像選択

  get 'serapoke' => 'serapoke#index', as: :serapoke#せらポケ

  get 'diploma' => 'diploma#index', as: :diploma#ディプロマ

  get '/admin/:student_id/student_edit' => 'admins#student_edit', as: :student_edit_admin#student編集

  post '/students/import' => 'students#import', as: :import_students#csvファイル取り込み

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :course_type, inclusion: { in: ["therapist_training","self_care"] }

  def self.import(file)
    i = 1
    CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
      # IDが見つかれば、レコードを呼び出し、見つからなければ、新しく作成
      student = find_by("id": i.to_s) || new

      # CSVからデータを取得し、設定する

      # hashのkeyを変更する
      hh = row.to_hash
      key_map = {}
      for ii in hh.keys do
        if ii == "名前"
          key_map.store(ii, "name")
        elsif ii == "メールアドレス"
          key_map.store(ii, "email")
        elsif ii == "電話番号"
          key_map.store(ii, "phone_number")
        else
          key_map.store(ii, ii)
        end
      end
      hh.transform_keys! {|k| key_map[k] }

      # hhから取ってくるカラムだけを選択してstudentに設定
      student.attributes = hh.slice(*updatable_attributes)

      # 型番の値によってcouse_typeを設定する
      if hh["型番"] == "M-H"
        student.attributes = { course_type: "therapist_training" }
      elsif hh["型番"] == "S-C"
        student.attributes = { course_type: "self_care" }
      else
        student.attributes = { course_type: "therapist_training" }
      end

      # 足らないカラムの値を追加
      student.attributes = { password: "password", password_confirmation: "password" }
      #保存する
      student.save
      i += 1
    end
  end

  def self.updatable_attributes
    ["name", "email", "phone_number"]
  end

end

app/controllers/students/sessions_controller.rb
class Students::SessionsController < Devise::SessionsController

  def create
    #元の認証ロジック
    #self.resource = warden.authenticate!(auth_options)

    #emailだけでログインできるように変更
    
    if params[:student]['email'].present?
      self.resource = Student.where(:email => params[:student]['email']).first
      if self.resource.present?
        set_flash_message(:notice, :signed_in) if is_flashing_format?
        sign_in(resource_name, resource)
        yield resource if block_given?
        if self.resource.course_type == "therapist_training"
          respond_with resource, :location => therapist_training_course_student_after_sign_in_path_for(resource)
        elsif self.resource.course_type == "self_care"
          respond_with resource, :location => self_care_course_student_after_sign_in_path_for(resource)
        end
        session[:student_id] = self.resource.course_type
      else
        flash[:danger] = "Eメールが違います"
        redirect_to new_student_session_path
      end
    else
      flash[:danger] = "Eメールを入力してください"
      redirect_to new_student_session_path
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # オブジェクトの準備
  before_action :set_student, only: [:show, :update, :destroy]
  # アクセス制限
  before_action :admin_only, only: [:index, :show, :update, :destroy]

  def index
    @students = Student.order(created_at: "ASC").paginate(page: params[:page], per_page: 10)
  end

  def update
    if @student.update_attributes(student_params)
      flash[:success] = "受講生情報を更新しました。"
      redirect_to @student
    else
      render :template=> "admins/student_edit", :locals=> { :@student=> @student }
   end
  end

  def destroy
    @student.destroy
    flash[:success] = "「#{@student.name}」のデータを削除しました。"
    redirect_to students_url
  end

  def import
    if params[:file].blank?
      flash[:danger] = "csvファイルが選択されていません。"
      redirect_to students_url
    else
      #fileはtmpに自動で一時保存される
      Student.import(params[:file])
      flash[:success] = "CSVファイルをインポートしました。"
      redirect_to students_url
    end
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end


    def student_params
      params.require(:student).permit(:name, :email, :course_type, :phone_number)
    end

end

app/helpers/students_helper.rb
module StudentsHelper

  # 受講生ログイン時のnavbar左端のロゴクリック時のパス
  def student_toppage_routes(student)
    return therapist_training_course_path(current_student) if student.course_type == "therapist_training"
    return self_care_course_path(current_student) if student.course_type == "self_care"
  end

  #navbar右端のアイコンからマイページ選択時のパス
  def mypage_routes(student)
    return therapist_training_course_show_path(current_student) if student.course_type == "therapist_training"
    return self_care_course_show_path(current_student) if student.course_type == "self_care"
  end

end

app/views/students/index.html.erb
<div class="student--title">
  <%= render 'layouts/flash_messages' %>
  <h1>受講生一覧</h1>
</div>

<%= form_with url: import_students_path, multipart: true, local: true do |f| %>
  <%= f.file_field :file, class: "file_field btn--resize" %>
  <%= f.submit "CSVをインポート", class: "btn btn-primary csv-button btn--resize" %>
<% end %>


<div class="container">
  <% @students.each_with_index do |student, n| %>
    <!--<div class="row">
      <div class="d-flex align-items-center border-top border-dark  student--index col-3">
        ID:
      </div>
      <div class="d-flex align-items-center border-top border-dark student--index col-5">
        <%= student.id %>
      </div>
      <% if current_staff.present? && current_staff.admin == true %>
        <div class="border-top d-flex align-items-center border-dark student--index col-2">
          <%= link_to "詳細", student_path(student), class: "btn btn-info btn--resize show#{n}" %>
        </div>
        <div class="border-top d-flex align-items-center border-dark student--index col-2">
          <%= link_to "削除", student, method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn-danger btn--resize delete#{n}" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="d-flex align-items-center border-top student--index col-3">
        名前:
      </div>
      <div class="border-top d-flex align-items-center student--index col-9">
        <%= link_to student.name, student_edit_admin_path(student_id: student.id), class: "edit#{n}" %>
      </div>
    </div>-->
    <div class="row">
      <div class="d-flex align-items-center border-top border-dark  student--index col-3">
        名前:
      </div>
      <div class="d-flex align-items-center border-top border-dark student--index col-5">
        <%= link_to student.name, student_edit_admin_path(student_id: student.id), class: "edit#{n}" %>
      </div>
      <% if current_staff.present? && current_staff.admin == true %>
        <div class="border-top d-flex align-items-center border-dark student--index col-2">
          <%= link_to "詳細", student_path(student), class: "btn btn-info btn--resize show#{n}" %>
        </div>
        <div class="border-top d-flex align-items-center border-dark student--index col-2">
          <%= link_to "削除", student, method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn-danger btn--resize delete#{n}" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="d-flex align-items-center border-top student--index col-3">
        Eメール:
      </div>
      <div class="border-top d-flex align-items-center student--index col-9">
        <%= student.email %>
      </div>
    </div>
        <div class="row">
      <div class="d-flex align-items-center border-top student--index col-3">
        電話番号:
      </div>
      <div class="border-top d-flex align-items-center student--index col-9">
        <%= student.phone_number %>
      </div>
    </div>
    <div class="row">
      <div class="d-flex align-items-center border-top student--index col-3">
        コース:
      </div>
      <div class="border-top d-flex align-items-center student--index col-9">
        <%= student.course_name %><!--「course_name」はstudent_decoratorに記載-->
      </div>
    </div>
  <% end %>
</div>
<br>
<%= will_paginate(@pusers, :previous_label => ' &lt 前へ', :next_label => '次へ &gt', class: "pagination justify-content-center mt-6 mb-7 btn--resize", renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
<%= link_to "戻る", admin_screen_path, class: "btn btn-secondary btn--resize" %>

app/views/students/show.html.erb
<div class="student--title">
  <%= render 'layouts/flash_messages' %>
  <h1>受講生詳細</h1>
</div>
<div class="container">
  <!--<div class="row">
    <div class="d-flex align-items-center border student--show col-3">
      ID:
    </div>
    <div class="d-flex align-items-center border-right border-top border-bottom student--show col-9">
      <%= @student.id %>
    </div>
  </div>-->
  <div class="row">
    <div class="d-flex align-items-center border student--show col-3">
      名前:
    </div>
    <div class="d-flex align-items-center border-right border-top border-bottom student--show col-9">
      <%= @student.name %>
    </div>
  </div>
  <div class="row">
    <div class="d-flex align-items-center border student--show col-3">
      Eメール:
    </div>
    <div class ="d-flex align-items-center border-right border-top border-bottom student--show col-9">
      <%= @student.email %>
    </div>
  </div>
  <div class="row">
    <div class="d-flex align-items-center border student--show col-3">
      電話番号:
    </div>
    <div class="d-flex align-items-center border-right border-top border-bottom student--show col-9">
      <%= @student.phone_number %>
    </div>
  </div>
  <div class="row">
    <div class="d-flex align-items-center border student--show col-3">
      コース:
    </div>
    <div class="d-flex align-items-center border-right border-top border-bottom student--show col-9">
      <%= @student.course_name %><!--「course_name」はstudent_decoratorに記載-->
    </div>
  </div>
</div>
<br>
<%= link_to "戻る", students_path, class: "btn btn-secondary btn--resize" %>