config/routes.rb
Rails.application.routes.draw do
  #rootを受講生ログイン画面に設定
  devise_scope :student do
    root 'therapist_training_course#index', as: :public_root, constraints: LoggedInConstraint.new("therapist_training")
    root 'self_care_course#index', constraints: LoggedInConstraint.new("self_care")
    root 'admin_screen#index', constraints: LoggedInConstraint.new("true")
    root 'staffs_screen#index', constraints: LoggedInConstraint.new("false")
    root "students/sessions#new", constraints: LoggedInConstraint.new("")
  end

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }
  devise_for :students, :controllers => {
    :sessions => 'students/sessions'
  }

  get 'therapist_training_course' => 'therapist_training_course#index', as: :therapist_training_course#セラピスト養成コース画面トップページ
  get 'self_care_course' => "self_care_course#index", as: :self_care_course#セルフケアコース画面トップページ
  get 'therapist_training_course/:id' => 'therapist_training_course#show', as: :therapist_training_course_show#セラピスト養成コース マイページ
  get 'self_care_course/id' => 'self_care_course#show', as: :self_care_course_show#セルフケアコース マイページ

  get 'admin_screen' => 'admin_screen#index', as: :admin_screen#管理者画面
  get 'staffs_screen' => 'staffs_screen#index', as: :staffs_screen#スタッフ画面

  resources :staffs do
    resources :blogs #スタッフブログ
  end

  resources :schedules#開講スケジュール

  resources :students#ユーザー管理

  resources :uploads, only: [:create, :destroy]

  resources :backgrounds#背景画像選択

  get 'serapoke' => 'serapoke#index', as: :serapoke#せらポケ

  get 'diploma' => 'diploma#index', as: :diploma#ディプロマ

  get '/admin/:student_id/student_edit' => 'admins#student_edit', as: :student_edit_admin#student編集

  post '/students/import' => 'students#import', as: :import_students#csvファイル取り込み

end

app/models/background.rb
class Background < ApplicationRecord
  mount_uploader :image, BackgroundUploader
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_action :admin_only
  before_action :set_background, only:[:update, :destroy]

  def index
    @background = Background.new
    @backgrounds = Background.all.order(created_at: :desc)
  end

  def create
    @background = Background.new(background_params)
    if @background.save
      flash[:notice] = "画像を追加しました"
      redirect_to backgrounds_url
    else
      render :index
    end
  end

  def update
    @no_background = Background.where(default: true)
    @no_background.update_all(default: false)
    @background.update_attributes(default: true)
    flash[:notice] = "背景画像に設定しました"
    redirect_to backgrounds_url
  end

  def destroy
    @background.destroy
    flash[:info] = "画像を削除しました。"
    redirect_to backgrounds_url
  end

  private

    def set_background
      @background = Background.find(params[:id])
    end


    def background_params
      params.require(:background).permit(:image)
    end

end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/views/backgrounds/index.html.erb
<%= render 'layouts/flash_messages' %>

<div class="container col-10 col-md-10 col-lg-4">
  <div class="background-new">
    <h1>背景画像一覧</h1>
    <%= form_with(model: @background, local: true) do |f| %>
      <%= f.label "新しい画像を追加" %>
      <%= f.file_field :image, class: "form-control" %>
      <%= f.submit "追加", class: "btn btn-primary mt-2" %>
      <%= link_to "キャンセル", backgrounds_path, class: "btn btn-secondary mt-2" %>
    <% end %>
  </div>
</div>

<div class="bg-index container col-10 col-md-10 col-lg-10">
  <% @backgrounds.each do |bg| %>
    <div class="background-index mt-3 mr-2">
      <div class="background">
        <%= image_tag bg.image.url if bg.image? %>
      </div>
      <div class="select-btn">
        <div class="text-center mb-2">
          <% if bg.default == true %>
            <%= "背景に設定中" %>
          <% else %>
            <%= link_to "背景に設定", background_path(bg.id), method: :patch, data: {confirm: "背景画像に設定します"}, class:"btn btn-primary btn-sm" %>
            <%= link_to "削除", background_path(bg.id), data: { confirm: "削除してよろしいですか？" }, method: :delete, class: "btn btn-danger btn-sm" %>
          <% end %>
        </div>    
      </div>
    </div>  
  <% end %>
</div> 
<%= link_to "戻る", admin_screen_path, class: "btn btn-secondary mt-3 ml-3" %>