config/routes.rb
Rails.application.routes.draw do
  #rootを受講生ログイン画面に設定
  devise_scope :student do
    root 'therapist_training_course#index', as: :public_root, constraints: LoggedInConstraint.new("therapist_training")
    root 'self_care_course#index', constraints: LoggedInConstraint.new("self_care")
    root 'admin_screen#index', constraints: LoggedInConstraint.new("true")
    root 'staffs_screen#index', constraints: LoggedInConstraint.new("false")
    root "students/sessions#new", constraints: LoggedInConstraint.new("")
  end

  devise_for :staffs, :controllers => {
    :registrations => 'staffs/registrations',
    :sessions => 'staffs/sessions'
  }
  devise_for :students, :controllers => {
    :sessions => 'students/sessions'
  }

  get 'therapist_training_course' => 'therapist_training_course#index', as: :therapist_training_course#セラピスト養成コース画面トップページ
  get 'self_care_course' => "self_care_course#index", as: :self_care_course#セルフケアコース画面トップページ
  get 'therapist_training_course/:id' => 'therapist_training_course#show', as: :therapist_training_course_show#セラピスト養成コース マイページ
  get 'self_care_course/id' => 'self_care_course#show', as: :self_care_course_show#セルフケアコース マイページ

  get 'admin_screen' => 'admin_screen#index', as: :admin_screen#管理者画面
  get 'staffs_screen' => 'staffs_screen#index', as: :staffs_screen#スタッフ画面

  resources :staffs do
    resources :blogs #スタッフブログ
  end

  resources :schedules#開講スケジュール

  resources :students#ユーザー管理

  resources :uploads, only: [:create, :destroy]

  resources :backgrounds#背景画像選択

  get 'serapoke' => 'serapoke#index', as: :serapoke#せらポケ

  get 'diploma' => 'diploma#index', as: :diploma#ディプロマ

  get '/admin/:student_id/student_edit' => 'admins#student_edit', as: :student_edit_admin#student編集

  post '/students/import' => 'students#import', as: :import_students#csvファイル取り込み

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  mount_uploader :image, ScheduleUploader
  validates :date, presence: true
  validates :title, presence: true


#検索機能--------------------------------------------------------------------
  enum public_status: {公開: 1, 非公開: 2, 中止: 3, 延期: 4}

  #開催エリアによる絞り込み
  scope :get_by_area, ->(area) {
    where(area: area)
  }
  #種別による絞り込み
  scope :get_by_event_type, ->(event_type) {
    where(event_type: event_type)
  }
  #講師による絞り込み
  scope :get_by_teacher, ->(teacher) {
    where(teacher: teacher)
  }
#----------------------------------------------------------------------------

#会員限定の絞り込み-------------------------------------------------------------
  scope :get_by_members, ->(judgement_of_members) {
    where(judgement_of_members: true)
  }
#----------------------------------------------------------------------------

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :staff_only, only: [:new, :edit, :destroy]


  # スケジュール一覧
  def index
    if current_staff.present?
      @schedules = Schedule.paginate(page: params[:page], per_page: 9).order(date: "DESC")
    else
      @schedules = Schedule.paginate(page: params[:page], per_page: 9).where.not(public_status: "非公開").order(date: "DESC")
    end
    # if params[:search].present?
    #   @schedules = Schedule.paginate(page: params[:page]).search(params[:search]) 
    # end

  #検索機能-------------------------------------------------------------------
    if params[:area].present?
      @schedules = @schedules.paginate(page: params[:page], per_page: 6).get_by_area params[:area]
      # @schedules = Schedule.areas.key(params[:area].to_i)
    end
    if params[:event_type].present?
      @schedules = @schedules.paginate(page: params[:page], per_page: 6).get_by_event_type params[:event_type]
    end
    if params[:teacher].present?
      @schedules = @schedules.paginate(page: params[:page], per_page: 6).get_by_teacher params[:teacher]
    end
  #--------------------------------------------------------------------------    

  #会員限定の絞り込み-----------------------------------------------------------
    if params[:judgement_of_members] == "1"
      @schedules = @schedules.paginate(page: params[:page], per_page: 6).get_by_members params[:judgement_of_members]
    end
  #-------------------------------------------------------------------------- 
  end

  # スケジュール詳細
  def show
  end

  # スケジュール作成
  def new
    @schedule = Schedule.new
    # @staffs = Staff.where.not(admin: true)
  end

  # スケジュール作成・保存
  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:success] = '新規投稿しました。'
      redirect_to @schedule
    else
      render :new
    end
  end

  # スケジュール編集
  def edit
    # @staffs = Staff.where.not(admin: true)
  end

  # スケジュール更新
  def update
    # if @schedule.update_attributes!(schedule_params)
    if @schedule.update_attributes(schedule_params)
      flash[:success] = "更新しました。"
      redirect_to @schedule
    else
      flash.now[:danger] = "#{@schedule.errors.full_messages}" if @schedule.errors.present?
      render :edit
    end
  end

  # スケジュール削除
  def destroy
    @schedule.destroy
    flash[:success] = "#{@schedule.date}の投稿を削除しました。"
    redirect_to schedules_url
  end


  private

      def schedule_params
        params.require(:schedule).permit(:date, :area, :place, :teacher, :event_type, :title, :details, :image, :public_status, :judgement_of_members)
      end

      def staff_only
        unless current_staff.present?
          flash[:danger] = "許可されていない操作です。"
          redirect_to schedules_url
        end
      end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with model: @schedule, local: true  do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <%= f.label :date, class: "label-#{yield(:class_text)}" %>
  <%= f.date_field :date, class: "form-control" %>

  <%= f.label :event_type, class: "label-#{yield(:class_text)}" %>
  <%= f.select :event_type, ['イベント', '講座', 'セミナー', 'その他'], { include_blank: '選択してください'}, class: "form-control" %>

  <%= f.label :title, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :area, class: "label-#{yield(:class_text)}" %>
  <%= f.select :area, ['関東', '関西', '中国・四国', '九州', 'オンライン'], { include_blank: '選択してください'}, class: "form-control" %>

  <%= f.label :teacher, class: "label-#{yield(:class_text)}" %>
  <%= f.collection_select :teacher, Staff.all, :name, :name, { include_blank: '選択してください'}, class: "form-control" %>

  <%= f.label :details, class: "label-#{yield(:class_text)}" %>
  <%= f.text_area :details, 'data-provider': :summernote %>

  <%= f.label "サムネイル画像を選択", class: "label-#{yield(:class_text)}" %><br>
    <%= image_tag @schedule.image.url(:thumb), id: :img_prev if @schedule.image? %>
  <%= f.file_field :image, id: "schedule_image", class: "form-control" %>

  <%= f.label :public_status, class: "label-#{yield(:class_text)}" %><br>
  <div class="col-sm-12 btn-group" data-toggle="buttons">
    <label class="btn btn-outline-secondary <%= "active" if @schedule.public_status == '公開' %>" style="width:50%">
      <%= f.radio_button :public_status, '公開', {class: "radio_view"} %> 公開
    </label>
    <label class="btn btn-outline-secondary <%= "active" if @schedule.public_status == '非公開' %>" style="width:50%">
      <%= f.radio_button :public_status, '非公開', {class: "radio_view"} %> 非公開
    </label>
    <label class="btn btn-outline-secondary <%= "active" if @schedule.public_status == '中止' %>" style="width:50%">
      <%= f.radio_button :public_status, '中止', {class: "radio_view"} %> 中止
    </label>
    <label class="btn btn-outline-secondary <%= "active" if @schedule.public_status == '延期' %>" style="width:50%">
      <%= f.radio_button :public_status, '延期', {class: "radio_view"} %> 延期
    </label>
  </div><br>

  <%= f.check_box :judgement_of_members %>
  <%= f.label :会員限定, class: "label-#{yield(:class_text)}" %><br>

  <div class="row center-block text-center">
    <div class="col-1">
    </div>
    <div class="col-5">
      <%= link_to "戻る", 'javascript:history.back()', class: "btn btn-secondary btn-block" %>
    </div>
    <div class="col-5">
      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    </div>
  </div>
<% end %>

<!-- 編集画面にサムネイルの画像を表示させる-->
<script type="text/javascript">
$(function() {
 function readURL(input) {
   if (input.files && input.files[0]) {
     var reader = new FileReader();
     reader.onload = function (e) {
       $('#img_prev').attr('src', e.target.result);
     }
     reader.readAsDataURL(input.files[0]);
   }
 }
 $("#schedule_image").change(function(){
   readURL(this);
 });
});
</script>

app/views/schedules/edit.html.erb
<% provide(:class_text, 'schedule-edit') %>
<% provide(:button_text, '変更する') %>

<h1>イベント／講座編集</h1><br>


<div class="row">
  <div class="col-md-8 offset-md-2">
      <%= render 'form' %>
  </div>
</div>

<!-- 画像ファルは5MBまで、というメッセージ（ただの警告） -->
<script type="text/javascript">
  $('#schedule_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('ファイルサイズは5MBまでです。小さいサイズのファイルを選択してください。');
    }
  });
</script>

app/views/schedules/index.html.erb
<%= render 'layouts/flash_messages' %>
<% if params[:area].present? || params[:event_type].present? || params[:teacher].present? %>
  <h1>検索結果</h1>
<% else %>
  <h1>イベント / 講座一覧</h1>
<% end %>


<!--開講スケジュール一覧テーブル-->
<div class="col-md-10 offset-md-1">

  <!--検索フォーム------------------------------------------------------------------------------------------------>
  <div class="seach-results col-md-6 offset-md-8 row">
    <% if params[:area].present? || params[:event_type].present? || params[:teacher].present? %>
      <p>検索条件：</p>
    <% end %>
    <% if params[:area].present? %>
      <p>【<%= params[:area] %>】</p>
    <% end %>
    <% if params[:event_type].present? %>
      <p>【<%= params[:event_type] %>】</p>
    <% end %>
    <% if params[:teacher].present? %>
      <p>【<%= params[:teacher] %>】</p>
    <% end %>
  </div >  
  <div class="seach-forms col-md-4 offset-md-8"> <!--末尾に row を入れると検索フォーム幅が狭くなる-->
    <%= form_with(url: schedules_path, method: :get, local: true) do |f| %>
      <%= f.select :area, ['関東', '関西', '中国・四国', '九州', 'オンライン'], {prompt: "開催エリア"}, {class: 'form-control'} %>
      <%= f.select :event_type, ['イベント', '講座', 'セミナー', 'その他'], {prompt: "種別"}, {class: 'form-control'} %>
      <%= f.collection_select :teacher, Staff.all, :name, :name, {prompt: "セラピスト"}, {class: "form-control"} %>
      <%= f.submit "検索", class: "btn btn-info" %>
    <% end %>
  </div>
  <!--会員限定のみチェックボックス---------------------------------------------->
  <%# <label><input id="judgement_of_members" type="checkbox">会員限定のみ</label> %>
  <%= form_with(url: schedules_path, method: :get, local: true) do |f| %>
    <%= f.check_box :judgement_of_members %>
    <%= f.label :会員限定のみ %>
    <%= f.submit "表示" %>
  <% end %>

  <%# <script>
    $(function(){
      $('#judgement_of_members').change(function(){
        $('.member-false').toggle();
      })
    })
  </script> %>
  <!-------------------------------------------------------------------------->    

  <% if current_staff.present? %>
    <div class="btn-schedule-new">
      <%= link_to "新規追加", new_schedule_path(@schedule), class: "btn btn-info" %>
    </div>
  <% end %>
  <div class="contents-wrap">
    <% @schedules.each do |s| %>
    <% if s.public_status == '非公開' %>
      <div class="contents-box-opacity member-<%= s.judgement_of_members %>">
    <% else %>
      <div class="contents-box member-<%= s.judgement_of_members %>">
    <% end %>
        <div class="contents">
            <%
=begin%>
 <%= l(s.created_at, format: :long) %> 
<%
=end%>
          <div class="mark-title">
            <div class="ml-4">
              <% if s.event_type == "イベント" %>
                <button type="button" class="btn btn-outline-success w-60 p-0">イベント</button>
              <% elsif s.event_type == "講座" %>
                <button type="button" class="btn btn-outline-primary w-60 p-0">講座</button>
              <% elsif s.event_type == "セミナー" %>
                <button type="button" class="btn btn-outline-warning w-40 p-0">セミナー</button>
              <% elsif s.event_type == "その他" %>
                <button type="button" class="btn btn-outline-secondary w-60 p-0">その他</button>
              <% end %>
            </div>
            <div class="only-members ml-1">
              <% if s.judgement_of_members == true %>
                <button type="button" class="btn btn-outline-danger p-0">会員限定</button>
              <% else %>
                <button type="button" class="btn btn-outline btn-sm" disabled>　</button>
              <% end %>
            </div>
          </div>  
          <div class="event-date">
            <% if s.date != nil %>
              <label>開催日：<%= l(s.date, format: :default) %></label><br>
            <% else %>
              <p></p>
            <% end %>
          </div>  
          <label><%= link_to (s.title), s %></label><br>
          <div class="thumbnail">
            <% if s.image? %>
              <% if s.public_status == '中止' %>
                <%= link_to (image_tag s.image.thumb.to_s), s, class: "thumb-image-message" %>
                <div class="cancel">中止</div>
              <% elsif s.public_status == '延期' %>
                <%= link_to (image_tag s.image.thumb.to_s), s, class: "thumb-image-message" %>
                <div class="postponed">延期</div>
              <% else %>
                <%= link_to (image_tag s.image.thumb.to_s), s, class: "thumb-image" %>
              <% end %>
            <% elsif s.public_status == '中止' %>
              <image src="/assets/default.jpg" width="200" height="200" class="thumb-image-message">
              <div class="cancel">中止</div>
            <% elsif s.public_status == '延期' %>
              <image src="/assets/default.jpg" width="200" height="200" class="thumb-image-message">
              <div class="postponed">延期</div>
            <% else %>
              <image src="/assets/default.jpg" width="200" height="200">
            <% end %>
          </div>
          <label class="mt-2">セラピスト名：<%= s.teacher %></label><br>
          <label>開催エリア：<%= s.area %></label><br>
          <% if current_staff.present? %>
            <%= link_to "編集", edit_schedule_path(s), class: "btn btn-primary" %>
            <%= link_to "削除", schedule_path(s), method: :delete,
                  data: {confirm: "削除してよろしいですか？" },
                  class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= will_paginate @schedules, :previous_label => ' &lt 前へ', :next_label => '次へ &gt', class: "pagination justify-content-center mt-6 mb-7 btn--resize", renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>　
  <div class="center">
    <% if params[:area].present? || params[:event_type].present? || params[:teacher].present? %>
      <%= link_to "<　一覧へ戻る", schedules_path, class: "btn btn-secondary" %>
    <% else %>
      <!-- 「staff_toppage_routes」はstaffs_helper.rbに記載 -->
      <% if current_staff.present? %>
        <%= link_to "<　戻る", staff_toppage_routes(current_staff), class: "btn btn-secondary" %>
      <% elsif current_student.present? %>
        <%= link_to "<　戻る", student_toppage_routes(current_student), class: "btn btn-secondary" %>
      <% else %>
        <%= link_to "<　戻る", 'https://www.eartherage.com/', class: "btn btn-secondary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/schedules/new.html.erb
<% provide(:class_text, 'schedule-new') %>
<% provide(:button_text, '作成する') %>

<h1>イベント／講座作成</h1><br>


<div class="row">
  <div class="col-md-8 offset-md-2">
      <%= render 'form' %>
  </div>
</div>

<!-- 画像ファルは5MBまで、というメッセージ（ただの警告） -->
<script type="text/javascript">
  $('#schedule_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('ファイルサイズは5MBまでです。小さいサイズのファイルを選択してください。');
    }
  });
</script>

app/views/schedules/show.html.erb
<div class="schedule-show container col-lg-8">
  <%= render 'layouts/flash_messages' %>
  <h3><%= @schedule.title %></h3>
  <!--<h6><%= l(@schedule.created_at, format: :long) %></h6>-->
  <!-- %= image_tag @schedule.image.url if @schedule.image? % -->

  <p><%== @schedule.details %></p>

  <div>
    <%= link_to "戻る", schedules_path, class: "btn btn-secondary" %>
  </div>
</div>